name: Deployment
on:
  push:
    branches:
      - gh-pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install --force
      - name: Build page
        run: npm run build
        env:
          CI: false
      - name: Deploy
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          CI: false
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          repository: ${{ github.repository }}
          REACT_APP_LIDERBORD_ADDRESS: ${{secrets.REACT_APP_LIDERBORD_ADDRESS}}
          REACT_APP_LIDERBORD_CHAIN_ID: ${{secrets.REACT_APP_LIDERBORD_CHAIN_ID}}
          REACT_APP_MORALIS_APPLICATION_ID: ${{secrets.REACT_APP_MORALIS_APPLICATION_ID}}
          REACT_APP_MORALIS_SERVER_URL: ${{secrets.REACT_APP_MORALIS_SERVER_URL}}
          REACT_APP_MORALIS_SPEEDY_NODES_KEY: ${{secrets.REACT_APP_MORALIS_SPEEDY_NODES_KEY}}
          REACT_APP_MORALIS_CLIENT_ID: ${{secrets.REACT_APP_MORALIS_CLIENT_ID}}
          REACT_APP_BICONOMY_API_KEY_BSC_TESTNET: ${{secrets.REACT_APP_BICONOMY_API_KEY_BSC_TESTNET}}
          REACT_APP_BICONOMY_API_KEY_MUMBAI: ${{secrets.REACT_APP_BICONOMY_API_KEY_MUMBAI}}
          REACT_APP_BICONOMY_API_KEY_FUJI: ${{secrets.REACT_APP_BICONOMY_API_KEY_FUJI}}